version: 2
jobs:
  build-and-test:
    macos:
      xcode: "10.0.0"

    steps:
      - checkout

      - run:
          name: Carthage
          command: |
            brew update
            brew outdated carthage || brew upgrade carthage
            carthage update
      - run:
          name: Install Swiftlint
          command: brew install swiftlint

      - run:
          name: Build macOS and watchOS
          command: |
            set -o pipefail && xcodebuild -project QminderAPI.xcodeproj -scheme QminderAPI-macOS CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO clean build | xcpretty --color
      - run:
          name: Start websockets test server
          command: |
            cd TestWebsockets
            brew install libressl
            brew install pkg-config
            swift build
            .build/debug/TestWebsockets&
            cd ..
            set -o pipefail && xcodebuild -project QminderAPI.xcodeproj -scheme QminderAPI-iOS -destination 'platform=iOS Simulator,name=iPhone X' CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO -enableCodeCoverage YES clean test build | xcpretty --color
            set -o pipefail && xcodebuild -project QminderAPI.xcodeproj -scheme QminderAPI-tvOS -destination 'platform=tvOS Simulator,name=Apple TV 4K' CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO -enableCodeCoverage YES clean test build | xcpretty --color

      - run:
          name: Codeconv
          command: |
            sed -i"any_symbol" "s/SLACK_KEY/${SLACK_KEY}/" codecov.yml
            bash <(curl -s https://codecov.io/bash)

      - run:
          name: SwiftPM Build
          command: swift build

      - run:
          name: Update ruby and cocoapods
          command: |
            echo "ruby-2.4" > ~/.ruby-version
            sudo gem install cocoapods --no-document
            curl https://cocoapods-specs.circleci.com/fetch-cocoapods-repo-from-s3.sh | bash -s cf
      - run:
          name: Check code coverage
          command: |
            brew install jq
            sudo gem install atomos --no-document
            sudo gem install jazzy --no-document
            jazzy
            ./documentation-coverage.sh
      - run:
          name: Pod lib lint
          command: pod lib lint --allow-warnings
workflows:
  version: 2
  nightly:
     triggers:
       - schedule:
           cron: "0 0 * * *"
           filters:
             branches:
               only:
                 - master
     jobs:
       - build-and-test
  build-and-test:
    jobs:
      - build-and-test
